apiVersion: v1
kind: Service
metadata:
    name: websvc
spec:
   type: ClusterIP
   selector:
      app: lwapp
   ports:
   - name: monport
     port: 1234
     targetport: 3000
   - name: webport
     port: 8080
     targetport: 80