apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mymonitor-rs
spec:
  replicas: 3
  selector:
     matchLabels:
       app: "monitorapp"
       dc: "IN"
       env: "prod"	 
  template:
     metadata:
       labels:
         dc: "IN"
         app: "monitorapp"
         env: "prod"
     spec:
        containers:
        - name: "mymonitortool"
          image: "vimal13/grafana"